### ISSUE TITLE
Comparison with prior art

### ISSUE THREAD

**Issue by dandv** [alvinhui/nlp-mitie#2]
Thanks for publishing this! Wondering how it compares with @bhelx's https://github.com/bhelx/mitie. Thanks.

**Comment by alvinhui** [comment]
`bhelx/mitie` is a semi-finished product, It does not contain the logic of training.

**Comment by bhelx** [comment]
Thanks for the reminder. I decided to archive the project and added a warning in the README: https://github.com/bhelx/mitie
